In [ ]:
import pandas as pd
from google.colab import drive
get_ipython().run_line_magic('matplotlib', 'inline')
import seaborn as sns
import requests
import io
from sklearn.ensemble import VotingClassifier, StackingClassifier
from sklearn.model_selection import train_test_split, cross_validate, KFold
from sklearn.metrics import f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

drive.mount('/Drive')

Mounted at /Drive

In [ ]:
# 
#Downloading the csv file from your GitHub account

url = "https://raw.githubusercontent.com/JulienJ-44/rakuteam/main/Features/data_features_final.csv" # Make sure the url is the raw version of the file on GitHub
download = requests.get(url).content

# Reading the downloaded content and turning it into a pandas dataframe

df = pd.read_csv(io.StringIO(download.decode('utf-8')))

#Drop useless columns
df = df.drop(["Unnamed: 0.1","Unnamed: 0","imageid", "prdtypecode.1","productid", "designation","description", "best_idf"], axis=1)

# Printing out the first 5 rows of the dataframe

df.head()

# df = pd.read_csv('/Drive/My Drive/Colab/data_features_final.csv',index_col= 'productid')
# df = df.drop(columns=['Unnamed: 0','Unnamed: 0.1', 'prdtypecode.1','imageid','best_idf','designation','description'])

    productid  ...  descri_char_count (w/o space)
0  3804725264  ...                              3
1   436067568  ...                              3
2   201115110  ...                            652
3    50418756  ...                              3
4   278535884  ...                            180

[5 rows x 74 columns]

In [ ]:
# df.info()

In [ ]:

df['class'] = df['prdtypecode']
df = df.drop('prdtypecode', axis=1)
print(df.head())
# ​
df = df.replace({'class': {10: 1, 2280:2,   50:3, 1280:4, 2705:5, 2522:6, 2582:7, 1560:8, 1281:9, 1920:10, 2403:11,
       1140:12, 2583:13, 1180:14, 1300:15, 2462:16, 1160:17, 2060:18,   40:19,   60:20, 1320:21, 1302:22,
       2220:23, 2905:24, 2585:25, 1940:26, 1301:0}})

target = df['class']

features = df.drop(['class'], axis=1)

    productid     blanc  ...  descri_char_count (w/o space)  class
0  3804725264  0.896177  ...                              3     10
1   436067568  0.804087  ...                              3   2280
2   201115110  0.925060  ...                            652     50
3    50418756  0.476548  ...                              3   1280
4   278535884  0.781337  ...                            180   2705

[5 rows x 74 columns]

In [ ]:
#Prepare trainning and test data
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state = 123)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)

X_train  = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from time import time
t0 = time()
# {}
clf1 = RandomForestClassifier(max_features ='sqrt', n_jobs = -1,n_estimators = 500)
clf1.fit(X_train, y_train)

y_pred = clf1.predict(X_test)
dfcross=pd.crosstab(y_test.ravel(), y_pred, rownames=['Realité'], colnames=['Prédiction'], normalize=1)

print('Processing time: {} mins'.format(round((time() - t0) / 60, 2)))

classif = classification_report(y_test, y_pred)
print(classif)

Processing time: 2.52 mins
              precision    recall  f1-score   support

           0       0.94      0.67      0.78       154
           1       0.47      0.59      0.53       601
           2       0.71      0.79      0.75       964
           3       0.75      0.62      0.68       341
           4       0.61      0.66      0.63       944
           5       0.62      0.81      0.71       536
           6       0.68      0.75      0.71       993
           7       0.76      0.56      0.64       524
           8       0.61      0.76      0.68       967
           9       0.55      0.35      0.43       415
          10       0.90      0.86      0.88       866
          11       0.69      0.75      0.72       979
          12       0.68      0.64      0.66       552
          13       0.85      0.96      0.90      2045
          14       0.78      0.45      0.57       139
          15       0.92      0.88      0.90      1006
          16       0.78      0.72      0.75       298
          17       0.81      0.88      0.84       791
          18       0.75      0.72      0.73      1060
          19       0.63      0.57      0.60       475
          20       0.98      0.81      0.88       176
          21       0.66      0.55      0.60       635
          22       0.90      0.64      0.75       505
          23       0.92      0.52      0.66       151
          24       0.99      0.99      0.99       165
          25       0.90      0.60      0.72       527
          26       0.86      0.68      0.76       175

    accuracy                           0.74     16984
   macro avg       0.77      0.70      0.72     16984
weighted avg       0.75      0.74      0.74     16984

In [ ]:
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score

params_clf1 = {'n_estimators': [ 250, 500, 1000],
                'min_samples_leaf': [1, 3, 5],
                'max_features': ['sqrt', 'log2']}

gridcv = GridSearchCV(clf1, param_grid=  params_clf1, scoring= 'accuracy', cv = 3)

In [ ]:

t0 = time()

gridcv.fit(X_train, y_train)


pd.DataFrame(gridcv.cv_results_)[['params', 'mean_test_score' , 'std_test_score']]

print('Processing time: {} mins'.format(round((time() - t0) / 60, 2)))

Processing time: 96.49 mins

In [ ]:
ypred_proba = clf1.predict_proba(X_test)

In [ ]:
df_tosave=pd.DataFrame(ypred_proba)
path = '/Drive/My Drive/Colab'
df_tosave.to_csv(f'{path}/ypred_proba_RandomForest_Global_score0_74.csv')